AWSTemplateFormatVersion: "2010-09-09"
Resources:
  FondosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Fondos
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  ClientesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Clientes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  TransaccionesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Transacciones
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: cliente_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: cliente_id-index
          KeySchema:
            - AttributeName: cliente_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  NotificacionesTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: NotificacionesFondos
